[package]
name = "artifacts-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
artifacts-api = { workspace = true }
artifacts-core = { workspace = true }


ratatui = { version = "0.30.2", features = [ "serde" ] }
tracing = { workspace = true }
tui-big-text = { version = "0.8.8" }
